# API issues found along the way:
# Sorting doesn't work, wanted to sort from latest to oldest
# Offset doesn't work, it offsets but only within limit, which makes it impossible to paginate
query GetLaunches($limit: Int) {
  launches(limit: $limit) {
    upcoming
    launch_date_utc
    id
    mission_name
    links {
      flickr_images
      article_link
    }
    rocket {
      rocket_name
    }
    details
  }
}

query GetRockets {
  rockets {
    company
    id
    height {
      meters
    }
    diameter {
      meters
    }
    description
    cost_per_launch
    boosters
    mass {
      kg
    }
    name
    stages
    success_rate_pct
    wikipedia
    type
  }
}